"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Environment.py']
APP_NAME = "Space Invaders"
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Classical game 'Space Invaders' with some spice features",
        'CFBundleVersion': "6.9",
        'CFBundleShortVersionString': "0.6.9",
        'NSHumanReadableCopyright': u"Copyright © 2015, Team Spaghettification, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
